### PR TITLE
fix issue in pr#156

### PR DESCRIPTION
**Pull request by ac427**
my local test
```
In [15]: convert_scope_string_to_expression("foo='bar-bar'")                                                                                                                                                                                  
Out[15]: 
[True,
 [{'displayName': '',
   'isVariable': False,
   'operand': 'foo',
   'operator': 'equals',
   'value': ['bar-bar']}]]
In [16]: convert_scope_string_to_expression("foo='bar-bar' and qux='abc'")                                                                                                                                                                    
Out[16]: 
[True,
 [{'displayName': '',
   'isVariable': False,
   'operand': 'foo',
   'operator': 'equals',
   'value': ['bar-bar']},
  {'displayName': '',
   'isVariable': False,
   'operand': 'qux',
   'operator': 'equals',
   'value': ['abc']}]]

In [17]: convert_scope_string_to_expression("foo='bar-bar' and qux is 'abc'")                                                                                                                                                                 
Out[17]: 
[True,
 [{'displayName': '',
   'isVariable': False,
   'operand': 'foo',
   'operator': 'equals',
   'value': ['bar-bar']},
  {'displayName': '',
   'isVariable': False,
   'operand': 'qux',
   'operator': 'equals',
   'value': ['abc']}]]

```

### CODE REVIEW

**Comment by tembleking** [comment]
Thanks for the PR, this issue has also been addressed at #157

**Comment by ac427** [comment]
@tembleking , my original issue was with `-` in values. I think all the keys are `words.words` format.

**Comment by tembleking** [comment]
Yeah, @ac427 I believe this is addressed by the PR I sent you in the previous comment. If you take a look at the test in here:
https://github.com/sysdiglabs/sysdig-sdk-python/pull/157/commits/bd1a2265e1c088649ee268cb17bff915c31e9efd#diff-6b47da4f947d812dd23b67b38bb50037bf1915ebe768d76e1ba9aea5c41f6b56R40
You will see that this may be related to your issue.

**Comment by ac427** [comment]
```
[abc@foo 09:09:05 - tmp]$cd sysdig-sdk-python/sdcclient/monitor/dashboard_converters/
[abc@foo 09:09:55 - dashboard_converters]$ls
_dashboard_scope.py  _dashboard_versions.py  __init__.py
[abc@foo 09:09:56 - dashboard_converters]$ipython3
Python 3.8.6 (default, Sep 25 2020, 00:00:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import _dashboard_scope as foo                                                                                                                                                                                                        

In [2]: foo.convert_scope_string_to_expression("foo='bar-bar'")                                                                                                                                                                               
Out[2]: 
[False,
 'invalid scope: foo=\'bar-bar\', expecting one of {"\'" \'/[\\\\w\\\\.]+/\' \'"\'}']
```

**Pull request closed without merging**
